// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkokS4eiAtwnd6XUMuiN-xeZdDaaOQo74',
    appId: '1:927185211463:web:f87b6442879d45677de162',
    messagingSenderId: '927185211463',
    projectId: 'tasker-b8554',
    authDomain: 'tasker-b8554.firebaseapp.com',
    storageBucket: 'tasker-b8554.firebasestorage.app',
    measurementId: 'G-CMRFLNXFEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAND8r_rC2FzjUcKq8flPrdhkMmMDxnZR8',
    appId: '1:927185211463:android:9a6f9ded19577cb47de162',
    messagingSenderId: '927185211463',
    projectId: 'tasker-b8554',
    storageBucket: 'tasker-b8554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuu1GMnj4aZ5OJvCCNLgDoCO9Gq8nkh8',
    appId: '1:927185211463:ios:faa8e2441209ab537de162',
    messagingSenderId: '927185211463',
    projectId: 'tasker-b8554',
    storageBucket: 'tasker-b8554.firebasestorage.app',
    iosBundleId: 'com.example.tm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkuu1GMnj4aZ5OJvCCNLgDoCO9Gq8nkh8',
    appId: '1:927185211463:ios:faa8e2441209ab537de162',
    messagingSenderId: '927185211463',
    projectId: 'tasker-b8554',
    storageBucket: 'tasker-b8554.firebasestorage.app',
    iosBundleId: 'com.example.tm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkokS4eiAtwnd6XUMuiN-xeZdDaaOQo74',
    appId: '1:927185211463:web:4145cf849a1ee6277de162',
    messagingSenderId: '927185211463',
    projectId: 'tasker-b8554',
    authDomain: 'tasker-b8554.firebaseapp.com',
    storageBucket: 'tasker-b8554.firebasestorage.app',
    measurementId: 'G-BKRSTHYSC7',
  );
}
